stages:
  - tagChecking
  - publishProtosToLocalMavenRepo
  - build
  - test
  - sonarqube
  - deploy

tag-checker:
  stage: tagChecking
  script:
    - python3 tag_checker.py $CI_COMMIT_TAG
  only:
    - tags

junit-identityprovider:
  stage: test
  script:
    - cd identityprovider
    - ./gradlew test
  artifacts:
    paths:
      - identityprovider/build/jacoco/test-report.xml

junit-portfolio:
  stage: test
  script:
    - cd portfolio
    - ./gradlew test
  artifacts:
    paths:
      - portfolio/build/jacoco/test-report.xml

publish-protos-to-maven-local:
  stage: publishProtosToLocalMavenRepo
  script:
    - cd shared
    - ./gradlew clean
    - ./gradlew publishToMavenLocal

# builds all branches, except dev and master
branch-build:
  stage: build
  script:
    - cd identityprovider
    - ./gradlew bootJar
    - cd ../portfolio
    - ./gradlew bootJar
  artifacts:
    paths:
      - identityprovider/build/libs
      - portfolio/build/libs
  except:
    - tags
    - master
    - dev
    - Fix_Story-speed-up-groups

deploy-staging-identityprovider:
  stage: deploy
  script:
    - cd identityprovider
    - ./gradlew bootJar
    - rm -rf /home/gitlab-runner/staging-identityprovider/ || true
    - mkdir /home/gitlab-runner/staging-identityprovider/
    - mkdir -p /home/gitlab-runner/profile-images/staging/
    - cp -r ./build/libs /home/gitlab-runner/staging-identityprovider
    - cp ../runner/staging-identityprovider.sh /home/gitlab-runner/staging-identityprovider.sh
    - chmod u+x /home/gitlab-runner/staging-identityprovider.sh
    - touch /home/gitlab-runner/staging-identityprovider/.env
    - echo -e "SPRING_PROFILES_ACTIVE=deploy \nDATABASE_URL=$DB_STAGING_IDENTITY_URL \nDATABASE_USERNAME=$DB_STAGING_IDENTITY_USERNAME \nDATABASE_PASSWORD=$DB_STAGING_IDENTITY_PASSWORD \nIDENTITY_CONTEXT=$STAGING_IDENTITY_CONTEXT \nIMAGE_FOLDER=$STAGING_IMAGE_FOLDER \nIDENTITY_LOG_DIRECTORY=$STAGING_IDENTITY_LOG_DIRECTORY" > /home/gitlab-runner/staging-identityprovider/.env
    - sudo systemctl restart staging-identityprovider
  artifacts:
    paths:
      - identityprovider/build/libs
  environment:
    name: staging-identity
    url: https://csse-s302g4.canterbury.ac.nz/test/identity
  only:
    - dev
    - Fix_Story-speed-up-groups

deploy-staging-portfolio:
  stage: deploy
  script:
    - cd portfolio
    - ./gradlew bootJar
    - rm -rf /home/gitlab-runner/staging-portfolio/ || true
    - mkdir /home/gitlab-runner/staging-portfolio/
    - cp -r ./build/libs /home/gitlab-runner/staging-portfolio
    - cp ../runner/staging-portfolio.sh /home/gitlab-runner/staging-portfolio.sh
    - chmod u+x /home/gitlab-runner/staging-portfolio.sh
    - touch /home/gitlab-runner/staging-portfolio/.env
    - echo -e "SPRING_PROFILES_ACTIVE=deploy \nDATABASE_URL=$DB_STAGING_PORTFOLIO_URL \nDATABASE_USERNAME=$DB_STAGING_PORTFOLIO_USERNAME \nDATABASE_PASSWORD=$DB_STAGING_PORTFOLIO_PASSWORD \nPORTFOLIO_CONTEXT=$STAGING_PORTFOLIO_CONTEXT \nPORTFOLIO_LOG_DIRECTORY=$STAGING_PORTFOLIO_LOG_DIRECTORY" > /home/gitlab-runner/staging-portfolio/.env
    - sudo systemctl restart staging-portfolio
  artifacts:
    paths:
      - portfolio/build/libs
  environment:
    name: staging
    url: https://csse-s302g4.canterbury.ac.nz/test/portfolio
  only:
    - dev
    - Fix_Story-speed-up-groups

deploy-production-identityprovider:
  stage: deploy
  script:
    - cd identityprovider
    - ./gradlew bootJar
    - rm -rf /home/gitlab-runner/production-identityprovider/ || true
    - mkdir /home/gitlab-runner/production-identityprovider/
    - mkdir -p /home/gitlab-runner/profile-images/production/
    - cp -r ./build/libs /home/gitlab-runner/production-identityprovider
    - cp ../runner/production-identityprovider.sh /home/gitlab-runner/production-identityprovider.sh
    - chmod u+x /home/gitlab-runner/production-identityprovider.sh
    - touch /home/gitlab-runner/production-identityprovider/.env
    - echo -e "SPRING_PROFILES_ACTIVE=deploy \nDATABASE_URL=$DB_PRODUCTION_IDENTITY_URL \nDATABASE_USERNAME=$DB_PRODUCTION_IDENTITY_USERNAME \nDATABASE_PASSWORD=$DB_PRODUCTION_IDENTITY_PASSWORD \nIMAGE_FOLDER=$PRODUCTION_IMAGE_FOLDER \nIDENTITY_CONTEXT=$PRODUCTION_IDENTITY_CONTEXT \nIDENTITY_LOG_DIRECTORY=$PRODUCTION_IDENTITY_LOG_DIRECTORY" > /home/gitlab-runner/production-identityprovider/.env
    - sudo systemctl restart production-identityprovider
  artifacts:
    paths:
      - identityprovider/build/libs
  environment:
    name: production-identity
    url: https://csse-s302g4.canterbury.ac.nz/prod/identity
  only:
    - tags
    - master

deploy-production-portfolio:
  stage: deploy
  script:
    - cd portfolio
    - ./gradlew bootJar
    - rm -rf /home/gitlab-runner/production-portfolio/ || true
    - mkdir /home/gitlab-runner/production-portfolio/
    - cp -r ./build/libs /home/gitlab-runner/production-portfolio
    - cp ../runner/production-portfolio.sh /home/gitlab-runner/production-portfolio.sh
    - chmod u+x /home/gitlab-runner/production-portfolio.sh
    - touch /home/gitlab-runner/production-portfolio/.env
    - echo -e "SPRING_PROFILES_ACTIVE=deploy \nDATABASE_URL=$DB_PRODUCTION_PORTFOLIO_URL \nDATABASE_USERNAME=$DB_PRODUCTION_PORTFOLIO_USERNAME \nDATABASE_PASSWORD=$DB_PRODUCTION_PORTFOLIO_PASSWORD \nPORTFOLIO_CONTEXT=$PRODUCTION_PORTFOLIO_CONTEXT \nPORTFOLIO_LOG_DIRECTORY=$PRODUCTION_PORTFOLIO_LOG_DIRECTORY" > /home/gitlab-runner/production-portfolio/.env
    - sudo systemctl restart production-portfolio
  artifacts:
    paths:
      - portfolio/build/libs
  environment:
    name: production
    url: https://csse-s302g4.canterbury.ac.nz/prod/portfolio
  only:
    - tags
    - master


sonarqube-report:
  stage: sonarqube
  variables:
    GIT_DEPTH: 0
  script:
    - set JAVA_OPTS="-Xms2048m -Xmx4096m"
    - cd identityprovider
    - touch ./.env
    - echo -e "SONARQUBE_API_KEY=$SONARQUBE_API_KEY" > ./.env
    - ./gradlew sonarqube
    - cd ../portfolio
    - touch ./.env
    - echo -e "SONARQUBE_API_KEY=$SONARQUBE_API_KEY" > ./.env
    - ./gradlew sonarqube
  retry: 2